# Site settings
title: "Mine & Morsel"
description: "Uncover the perfect bite."
url: "https://mine-morsel.com"
instagram _username: mine_morsel

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Recommended for better SEO

# Minima social link
minima:
  social_links:
    instagram: mine_morsel
    facebook: mine_morsel

# Header navigation (optional)
header_pages:
  - menu.md
  - about.md
  - contact.md # Example: if you create a contact.md page

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
